[2025-04-29 20:31:25] [INFO]: Connected to MongoDB
[2025-04-29 20:31:25] [INFO]: Server running on port 3000
[2025-04-29 20:31:25] [ERROR]: Class constructor CustomError cannot be invoked without 'new'
[2025-04-29 20:31:25] [ERROR]: Test failed: expected 'Internal Server Error' to equal 'User already exists'
[2025-04-29 20:33:21] [ERROR]: Class constructor CustomError cannot be invoked without 'new'
[2025-04-29 20:33:55] [ERROR]: Class constructor CustomError cannot be invoked without 'new'
[2025-04-29 20:40:02] [INFO]: Connected to MongoDB
[2025-04-29 20:40:02] [INFO]: Server running on port 3000
[2025-04-29 20:40:02] [ERROR]: [CustomError] USER_ALREADY_EXISTS
[2025-04-29 20:40:02] [ERROR]: Test failed: expected 'USER_ALREADY_EXISTS' to equal 'User already exists'
[2025-04-29 20:40:14] [ERROR]: [CustomError] USER_ALREADY_EXISTS
[2025-04-29 20:51:58] [ERROR]: [CastError] Cast to ObjectId failed for value "681165ea3d90896f9c588de" (type string) at path "_id" for model "Pet"
[2025-04-29 20:57:15] [ERROR]: [CastError] Cast to ObjectId failed for value "681165ea3d90896f9c588de" (type string) at path "_id" for model "Pet"
[2025-04-29 20:58:06] [INFO]: Connected to MongoDB
[2025-04-29 20:58:06] [INFO]: Server running on port 3000
[2025-04-29 20:58:06] [ERROR]: [ReferenceError] CustomError is not defined
[2025-04-29 20:58:06] [ERROR]: [CastError] Cast to ObjectId failed for value "null" (type string) at path "_id" for model "Pet"
[2025-04-29 20:58:06] [ERROR]: [CustomError] USER_ALREADY_EXISTS
[2025-04-29 20:58:06] [ERROR]: Test failed: expected 'USER_ALREADY_EXISTS' to equal 'User already exists'
[2025-04-29 20:58:13] [ERROR]: [ReferenceError] PetModel is not defined
[2025-04-29 20:59:59] [ERROR]: [ReferenceError] PetModel is not defined
[2025-04-29 21:00:36] [ERROR]: [ReferenceError] PetModel is not defined
[2025-04-29 21:01:07] [INFO]: Connected to MongoDB
[2025-04-29 21:01:07] [INFO]: Server running on port 3000
[2025-04-29 21:01:13] [ERROR]: [ReferenceError] CustomError is not defined
[2025-04-29 21:01:54] [INFO]: Connected to MongoDB
[2025-04-29 21:01:54] [INFO]: Server running on port 3000
[2025-04-29 21:01:54] [ERROR]: [ReferenceError] CustomError is not defined
[2025-04-29 21:01:54] [ERROR]: [CastError] Cast to ObjectId failed for value "null" (type string) at path "_id" for model "Pet"
[2025-04-29 21:01:54] [ERROR]: [CustomError] USER_ALREADY_EXISTS
[2025-04-29 21:01:54] [ERROR]: Test failed: expected 'USER_ALREADY_EXISTS' to equal 'User already exists'
[2025-04-29 21:01:59] [ERROR]: [ReferenceError] CustomError is not defined
[2025-04-29 21:02:49] [ERROR]: [ReferenceError] CustomError is not defined
[2025-04-29 21:03:36] [ERROR]: [ReferenceError] CustomError is not defined
[2025-04-29 21:06:13] [INFO]: Connected to MongoDB
[2025-04-29 21:06:13] [INFO]: Server running on port 3000
[2025-04-29 21:06:19] [ERROR]: [CustomError] PET_ALREADY_EXISTS
[2025-04-29 21:07:29] [ERROR]: [CustomError] MISSING_PARAMETERS
[2025-04-29 21:10:07] [INFO]: Connected to MongoDB
[2025-04-29 21:10:07] [INFO]: Server running on port 3000
[2025-04-29 21:10:07] [ERROR]: [CustomError] MISSING_PARAMETERS
[2025-04-29 21:10:07] [ERROR]: [CastError] Cast to ObjectId failed for value "null" (type string) at path "_id" for model "Pet"
[2025-04-29 21:10:07] [ERROR]: [CustomError] USER_ALREADY_EXISTS
[2025-04-29 21:10:07] [ERROR]: Test failed: expected 'USER_ALREADY_EXISTS' to equal 'User already exists'
[2025-04-29 21:12:00] [ERROR]: [CustomError] MISSING_PARAMETERS
[2025-04-29 21:12:09] [ERROR]: [CustomError] PET_ALREADY_EXISTS
[2025-04-29 21:20:24] [ERROR]: [CustomError] PET_ALREADY_EXISTS
[2025-04-29 21:21:17] [INFO]: Connected to MongoDB
[2025-04-29 21:21:17] [INFO]: Server running on port 3000
[2025-04-29 21:21:17] [ERROR]: [CustomError] USER_ALREADY_EXISTS
[2025-04-29 21:21:17] [ERROR]: Test failed: expected 'USER_ALREADY_EXISTS' to equal 'User already exists'
[2025-04-29 21:22:56] [INFO]: Connected to MongoDB
[2025-04-29 21:22:56] [INFO]: Server running on port 3000
[2025-04-29 21:22:56] [ERROR]: [CustomError] USER_ALREADY_EXISTS
[2025-04-29 21:22:56] [ERROR]: Test failed: expected 'USER_ALREADY_EXISTS' to equal 'User already exists'
[2025-04-29 21:26:12] [INFO]: Connected to MongoDB
[2025-04-29 21:26:12] [INFO]: Server running on port 3000
